### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by lego19banana** [alexfornuto/arduino#2]
So I am a complete begginer with arduino and i dont know how to make this work. Can you explain it to me like i am a child so i can understand? Thank you.

**Comment by alexfornuto** [comment]
Hrmm, first activity on a brand new account, commenting on a dummy repo that hasn't been touched in 8 years... I'm thinking bot? Prove you're not a bot.

**Comment by lego19banana** [comment]
i made this acc just to ask this bcs i dont know i am no bot please help

**Comment by lego19banana** [comment]
yea so i made the code work now how do i wire the buzzer?

**Comment by alexfornuto** [comment]
Man, I dunno. I haven't touched this in years and years.

**Comment by lego19banana** [comment]
so i can do nothing?

**Comment by lego19banana** [comment]
thanks for telling me anyways

**Comment by alexfornuto** [comment]
There's lots you can do, but I can't help you.

Except to say this: Be it GitHub, Reddit, forums, or what-have-you, opening a thread with "Help" instead of a summary of the issue, and a text body as vague as you created, that's not going to garner a lot of help from the community you're interacting with. Be specific in all things; what you have, what you're trying to do, and what isn't working.
